# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

#pagination
paginate:      1
paginate_path: "/blog/page:num/"

# Setup
title:            Keshava Bharadwaj
tagline:          'Cloud, Openstack, Python, Microservices, *.*'
url:              http://www.keshavabharadwaj.com
shorturl:         keshavabharadwaj.com

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:           'Keshava Bharadwaj'
  url:            https://twitter.com/keshavab
  email:          kb.sankethi@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:           github.com/keshavab/keshavab.github.io

# List of pages in header of site.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'
